jtblin/kube2iam

cmd/server.go, cmd/store.go, main.go
Default role provides a fallback when annotation is missing.
closes #6
=> Add a default-role flag

README.md
use verbose flags and organize into different lines to make the command more readable.
=> expand iptables command to be more readable

README.md
The example command given in the docs doesn't work because the `--protocol` argument should be listed before `--dport` on the command line.
=> Fixed sample iptables command

cmd/server.go, main.go
This makes the max interval and max elapsed time configurabel for the
exponential backoff used when getting a role based on source IP.
The defaults are still the same e.g. 1 minute for MaxInterval and 15
minutes for the MaxElapsedTime.
Fix #28
=> Make backoff MaxInterval and MaxElapsedTime configurable

iptables/iptables.go, iptables/iptables_test.go
As per #37 calico networks are passed to kube2iam with the 'cali+' notation.
https://github.com/jtblin/kube2iam/pull/34 did not take this into consideration.
- Added conditional to `CheckInterfaceExists` that returns `nil` if a _+_ is detected
- Added a test to support this condition
=> Ignore wildcard interface names in interface check

cmd/server.go
We were running into some issues with assuming roles and had trouble finding the culprit.
The kube2iam container did not have the _--base-role-arn_ flag and we instead added them in the pod manifests explicitly. However, when requesting the role from the store, kube2iam made a check for the entire ARN against the role given in the route, which obviously failed.
While there might be another issue hidden in here, the additional log messages would have made it very obvious what was going on.
=> added log statements to make debugging assume-failures easier

cmd/iam.go, cmd/server.go
I built on top of what @negz made (https://github.com/jtblin/kube2iam/pull/51) to fix some bugs and test that roles could be assumed between two AWS accounts assuming the trust roles were set up properly.
My main driver behind this PR was to allow the assumption of a role from another AWS account, which can only be done with a full ARN specifier.
I tested a bunch of combinations including:
- no base ARN + full ARN default role + no annotation
- no base ARN + full ARN default role + full ARN annotation
- base ARN + full ARN default role + no annotation
- base ARN + full ARN default role + full ARN annotation
- base ARN + full ARN default role + simple role name annotation
Seems to be working fine.
=> Allow full ARN specification for roles, including cross AWS account

cmd/iam.go, cmd/server.go
This was an oversight on my part in https://github.com/jtblin/kube2iam/pull/53 - I was not familiar with the us-govt regions of AWS.
=> Fix ARN parsing to not break on aws-us-gov resources

Makefile, README.md, cmd/k8s.go, cmd/namespace.go, cmd/pod.go, cmd/server.go, cmd/store.go, main.go
This pull request implements a namespace restriction scheme. It's useful in multi-tennent clusters. Roles specified in pod annotations are checked against a list of allowed roles listed in an annotation on the pods namespace.
=> Namespace restriction

cmd/pod.go
Fixes #61 - When a pod changes, examines the relevant role annotation on the pod.
If it has been added, removed or updated then assumes role needs to be reassigned
=> Adding in annotation awareness to the OnChange listener

README.md, cmd/iam.go, cmd/server.go, glide.lock, glide.yaml, main.go
Related to:
https://github.com/jtblin/kube2iam/issues/13
=> Add default IAM role auto discovery

Makefile
Configure glide to not include vendor folder of dependencies.
This prevents vendoring multiple copies of glog and fixes #66 (https://github.com/kubernetes/kubernetes/issues/35096)
=> Run glide install with --strip-vendor

README.md
I'm not even sure this is universally correct, but it was under `kops` and it surprised the hell out of me.  I thought I'd add a note for the next poor soul.
=> Flannel needs cni0 not flannel0

iptables/iptables.go, iptables/iptables_test.go
Some small clean ups I spotted while reading the code.
- simplify error handling in AddRule
- unexport CheckInterfaceExists; it's not called outside iptables
- fix go vet errors in iptables_test.go
=> iptables: style clean ups

main.go
The runtime.GOMAXPROCS(runtime.NumCPU()) hack hasn't been needed since
Go 1.5. Let this hack rest in peace.
=> Remove runtime.GOMAXPROCS hack

README.md
I was a bit confused why this wasn't working at first, since I used the explicit name of the IAM role, but then realized it's probably the whole ARN.  I'm not sure if this was done for a specific reason but I figured I'd propose changing it to ARN as that's the only way I could get my roles to work.  
Thanks for the awesome project!
=> Replace role-name with role-arn

server/server.go
It's possible to scope roles to a custom path (arn:aws:iam::123456789012:role/team-a/test-role). The current implementation doesn't support this. Instead of test-role this fix will return team-a/test-role within the securityCredentialsHandler handler. See http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html for more details
about role paths.
=> Fix for roles with a custom path name

README.md, cmd/main.go, glide.lock, glide.yaml, namespace.go, pod.go, server/server.go, store/store.go
Add a --log-level flag to customize the log-level.
In our day-to-day operations we found the default Info log-level a bit to verbose
and would like to only see errors.
=> Customizable log level

iam/arn.go, iam/arn_test.go
I've found out that the regexp doesn't allow names with dots on itm but this is allowed by AWS.
I'm deploying kubernetes clusters with kops, and it creates IAM roles with the domains on it, so they have dots.
=> Change ARN Regexp to allow dots on role names

server/server.go
The AWS metadata service works differently on new instance types like
m5.large and c5.large.
The behavior on old instances is that if you call:
```
169.254.169.254/latest/meta-data/iam/security-credentials
```
It will redirect to:
```
169.254.169.254/latest/meta-data/iam/security-credentials/
```
Which will respond with the IAM role name.
On new instances there is no redirect, it just responds with the IAM role name directly.
Since kube2iam didn't intercept the URL without the slash, the pod will
initially get the worker node role and then try to request credentials for that
role, which kube2iam will deny.
Fix is to intercept both versions of the URL.
Fix #127
=> Fix missing redirect on m5/c5 instances

README.md, cmd/main.go, k8s/k8s.go, server/server.go
In clusters with 1000s of pods the memory used by each kube2iam
instance explodes because each kube2iam instance is storing information
about all pods on all nodes in memory.
This adds a flag `--node` for specifying the node name of kube2iam. If
set, it will limit the pods it's watching to those only on the same
node as the kube2iam instance.
=> Limit relevant pods to those on the same node as kube2iam

Dockerfile
Update alpine to 3.7
alpine 3.6 contains the following vulnerabilities:
- musl: https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-15650
- busybox: https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-16544 and https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-15873
=> Update alpine to 3.7 to address vulnerabilities

README.md
The README.md currently include instructions for what interface name/regex to use when configuring kube2iam with various Kubernetes networking solutions.   This change follows the existing format and adds those instructions for http://www.cilium.io based on a question asked on the Cilium slack channel.  The user validated that this configuration works with kube2iam w/Cilium.
=> Update README.md to mention interface for Cilium

README.md
Adds instructions for `amazon-vpc-cni-k8s` which is the default in the recently released EKS service.
Not sure if it needs more explanation around it being in EKS, as EKS users may come here looking for help.
=> Add amazon-vpc-cni-k8s to the host-interface examples

Makefile
gometallinter doesn't install govet anymore, manually install it so that CI
doesn't fail. Once this is merged the following error should go away: https://travis-ci.org/jtblin/kube2iam/builds/413586654#L787
=> Fix `make check` CI error

README.md
According to the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/)
> As of Kubernetes 1.8, you must specify a pod selector that matches the labels of the .spec.template. The pod selector will no longer be defaulted when left empty.
Without these changes, the following error is seen:
`error: error validating "kube2iam.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false`
Adding these changes satisfies validation.
=> Avoid the following error: `ValidationError(DaemonSet.spec)`

README.md, examples/eks-example.yml
While setting up kube2iam on my EKS cluster I struggled to get the service working until someone in the k8s slack  generously donated an hour of their time to help me debug it.
To facilitate faster setup for EKS users in the future I've added the following two changes
* Correct host interface for a default EKS cluster
* Example eks yaml file that is generic for EKS users and can be generally extended from the other documentation in the README
=> Add Documentation & Example For EKS

README.md, cmd/main.go, iam/iam.go, iam/iam_test.go, server/server.go
This one addresses #164 and allows the use of regional sts api endpoints instead of the default us-east-1 based endpoint. 
For users in regions other than us-east-1 this should mean slightly reduced latency in sts api calls.
By default the aws sdk will resolve the sts endpoint to `sts.amazonaws.com` as described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html#sts-regionalization). The regional api endpoint can only be set programmatically. Setting region via code or environment does not affect the endpoint, as indirectly described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#id_credentials_temp_enable-regions_writing_code).
To enable the use of this feature, a boolean flag `--use-regional-sts-endpoint` …
=> allow use of sts regional endpoints

README.md, cmd/main.go, iam/iam.go, server/server.go
We have long-running applications with pre-signed urls for videos. With a hard-coded 15mins TTL, videos would break, or if we did a re-sign + re-render, it would reset the video.
This PR adds a flag for the user to control the session TTL.
=> Add new flags for session TTL

server/server.go
`latencyNanoseconds` is a `float64` so the appropriate format is `%f` instead of `%d`. This will make the log line a bit more clear since it currently looks like this:
```
msg="GET /latest/meta-data/iam/security-credentials/foo (200) took %!d(float64=118126) ns"
```
=> use %f instead of %d for latency logging

pod.go
When a pod is deleted, the containers are issued a `SIGTERM` and its `deletionTimestamp` is set to now + `terminationGracePeriodSeconds`. After that time, a `SIGKILL` is issued and the pod is deleted (see [deletionTimestamp](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#objectmeta-v1-meta)).
For pods with longer terminationGracePeriodSeconds, its possible for the container process to refresh its credentials after the `SIGTERM` but before the `SIGKILL`. Prior to this PR, credentials were not provided and the process' cleanup would fail. This PR allows containers in the process of shutting down to refresh their credentials.
Fixes #172 
This means that we're now relying on the client's clock to be in sync with the master's clock but I would assume that is already a …
=> Allow pods being terminated to get credentials

kustomize/daemonset.yaml, kustomize/kustomization.yaml, kustomize/rbac.yaml
This adds a set of manifests for use as a [kustomize](https://github.com/kubernetes-sigs/kustomize) base layer. There might also an argument to be made for simplifying the README and pointing people to these instead.
=> Add kustomize config

README.md
This closes #170 by adding a warning about a possible race condition when using `--iptables=true` to the README.
=> Add warning regarding --iptables=true to README

Dockerfile
ADD is reserved for pulling in and automatically unpacking .tar/.gz files
COPY is for copying files across, which is what you're trying to achieve.
=> Change ADD to COPY

pod.go
Fixing a regression originating from #173, this was causing nil entries in the pod index which resulted in credentials failing to be issued.
See #178 for more information.
=> Do not check the pod's deletionTimestamp when determining if a pod is active

README.md
Even with calico the eni... interface name is used. See https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/calico.yaml, environment variable: FELIX_INTERFACEPREFIX
=> Update readme for eks

README.md, cmd/main.go, iam/iam.go, mappings/mapper.go, mappings/mapper_test.go, server/server.go
AWS supports a filtering system via `ExternalId` which allows to verify that the system attempting to assume the role is not making a mistake.
This adds the support of an externalId annotation (defaults to `iam.amazonaws.com/external-id`) so when the prod is created, an externalId can be provided and passed through as part of the `assume-role` operation.
=> Add support for externalId as an optional annotation

Dockerfile
Increment Alpine to 3.9 for security reasons
=> Update Dockerfile - new version of Alpine to 3.9

server/server.go
This PR makes res.duration expressed in milliseconds instead of nanoseconds.
Actually we are logging response duration as Nanoseconds, this is useless and causing an issue with Go default formatting of numbers to exponential notation:
```
time="2019-07-17T12:07:15Z" level=info msg="GET /latest/meta-data/iam/security-credentials/my-app (200) took 145540128.000000 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/my-app req.remote=1.1.1.1 res.duration=1.45540128e+08 res.status=200
```
=> Log res.duration as milliseconds

examples/eks-example.yml, kustomize/base/daemonset.yaml
Patch to mount xtables.lock in the Kustomize / EKS examples. This should be consistent with other services modifying iptables, such as kiam (https://github.com/integrii/kiam/blob/master/deploy/agent.yaml), kube-proxy (https://github.com/vdemeester/kubernetes/blob/master/cluster/addons/kube-proxy/kube-proxy-ds.yaml) and so forth, and help prevent these services from running into race conditions when modifying iptables concurrently.
=> mount /run/xtables.lock from host

mappings/mapper.go
Signed-off-by: Li Yi <denverdino@gmail.com>
The log.Debug is incorrect in the mappings/mapper.go
```
$ go version
go version go1.11.1 darwin/amd64
$ go test ./...
...
mappings/mapper.go:89: Debug call has possible formatting directive %s
...
FAIL	github.com/jtblin/kube2iam/mappings [build failed]
...
```
The 		
```
log.Debug("Unable to find an indexed namespace of %s", namespace)
```
should be
```
log.Debugf("Unable to find an indexed namespace of %s", namespace)
```
=> Fix the log.Debug issue in go test

README.md, cmd/main.go, k8s/k8s.go, mappings/mapper.go, mappings/mapper_test.go, metrics/metrics.go, namespace.go, namespace_test.go, pod.go, server/server.go
Trying to definitely fix issue https://github.com/jtblin/kube2iam/issues/244 maintaining retro compatibility.
When the flag is set to true (default is false) in case the cache lookups returns more than 1 result,
a query to the API server is issued and **a pod is returned only if it is running and not with host network**.
I've also added some metrics in order to track the amount of requests that are performed to the api server.
@Jacobious52 or any other maintainers can you please check this out?
=> Deal with duplicated IP in the pod cache

glide.lock, glide.yaml, k8s/k8s.go, mappings/mapper.go, mappings/mapper_test.go, namespace.go, namespace_test.go, pod.go
Stumbled over the issue that kube2iam can't AssumeRole for the pod.
Error that pods receives:
```
upgrade-manager-75966d7867-h9dr5 rolling-upgrade-controller time="2020-03-04T17:32:38Z" level=info msg="NoCredentialProviders: no valid providers in chain\ncaused by: EnvAccessKeyNotFound: failed to find credentials in the environment.\nSharedCredsLoad: failed to load profile, .\nEC2RoleRequestError: no EC2 instance role found\ncaused by: EC2MetadataError: failed to make EC2Metadata request\ncaused by: pod with specified IP not found\n"
```
Error in kube2iam:
```
E0304 17:33:33.671001       1 reflector.go:199] github.com/jtblin/kube2iam/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get "https://10.231.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-16-11 …
```
=> Upgrade client-go to new version

go.sum, server/server.go
Even after #270 we have experienced 403s from the metadata service while
using the AWS VPC CNI with any pods not using host networking. This
indicated that while the PUT requests for tokens were now working
correctly, the subsequent GET requests still had the `X-Forwarded-For`
header which AWS rejects with a 403.
=> :bug: Remove remote address header when any IMDSv2 tokens are used

Dockerfile
Bump Alpine to v3.12.1 to include openssl 1.1.1g for fixing [CVE-2020-1967](https://nvd.nist.gov/vuln/detail/CVE-2020-1967).
=> Use Alpine 3.12.1

.travis.yml, Makefile
This adds support for building Docker images for arm64 architecture.
Tested by pushing a tag and publishing the manifest to docker hub.
- Build: https://travis-ci.org/github/hligit/kube2iam/builds/748263791
- Manifest: https://hub.docker.com/layers/htli/kube2iam/hlitest/images/sha256-a05cc00c5fb1cbfed2092795293261dc85c6055f9f3505d0ea625ab3b0c1f198
=> Build and push docker image for arm64

charts/kube2iam/Chart.yaml, charts/kube2iam/README.md, charts/kube2iam/templates/daemonset.yaml, charts/kube2iam/values.yaml
Allow user to set maxUnavailable option for rolling updates in order
to speed up deployment times on large clusters.
=> [helm] Add maxUnavailable option for rolling updates

Dockerfile, Makefile
* Bumps go to 1.16, mitigating https://github.com/golang/go/issues/37436
* Uses `go install` instead of `go get` for installing build tools.
>go install now accepts arguments with version suffixes (for example, go install example.com/cmd@v1.0.0). This causes go install to build and install packages in module-aware mode, ignoring the go.mod file in the current directory or any parent directory, if there is one. This is useful for installing executables without affecting the dependencies of the main module. [source]
[SOURCE]: https://golang.org/doc/go1.16#go-command
=> Bump Go to 1.16

charts/kube2iam/Chart.yaml, charts/kube2iam/README.md, charts/kube2iam/templates/daemonset.yaml, charts/kube2iam/values.yaml
This PR adds a readiness probe. This is important in case it's needed kube2iam to be in ready status before scheduling any other workload that relies on kube2iam.
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
- fixes #
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
=> Add readiness probe to helm chart

charts/kube2iam/Chart.yaml, charts/kube2iam/values.yaml
Fixed to use a image that supports IMDSv2.
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
- fixes #328 
Use the latest 0.10.11 available on Docker Hub.
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
=> update to image 0.10.11 in helm chart

Dockerfile
Resolving underlying alpine vulnerabilities. Built locally to confirm it still builds
Trivy output (generated via `trivy image jtblin/kube2iam:0.11.1 --security-checks vuln --output kube2iam-0.11.1`):
```
jtblin/kube2iam:0.11.1 (alpine 3.14.3)
======================================
Total: 9 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 6, CRITICAL: 1)
┌──────────────┬────────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│   Library    │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                            Title                            │
├──────────────┼────────────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ busybox      │ …
```
=> chore: bump alpine version to resolve vulnerabilities

Dockerfile
Update Alpine to 3.20.2 to fix a number of CVEs in SSL libraries.
Would you be so kind to tag 0.11.3 with this? :heart: 
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
=> Update Alpine to 3.20.2

Dockerfile
Fixes Docker image builder.
- Docker builder [fails](https://app.circleci.com/pipelines/circleci/Tv5Xa331HXLx98iuW72Ug4/Po3PqWxjiikmpntHfiZoXW/31/workflows/9fc52610-1f97-4bfd-8687-3a32acc79d2e/jobs/49) due to Golang version, this PR upgrades the Golang version to build the image successfully.
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
=> fix: Upgrade Golang builder version to `1.22.7`

README.md
When kube2iam is configured with both --namespace-restrictions and --auto-discover-base-arn, we had some trouble finding how to allow it to assume a role in a different account.
By digging into the code we saw that it was possible by explicitly including the external base ARN to the iam.amazonaws.com/allowed-roles namespace annotation (before we only had regexp, which concerned only the roles in the current base ARN)
This PR aims to add a note about this behavior in the documentation to help users getting this information easier.
=> Add a note about assuming a role in a different account
